package de.mavid.main;

/**This Java source file was generated by the Gradle'init'task.*/

import org.junit.Test;

import de.mavid.data.Entities.Territory;
import de.mavid.data.controller.ReflectionAdapter;
import de.mavid.gui.model.TerritoryModel;

import static org.junit.Assert.*;

import org.junit.Assert;

public class AppTest {

	@Test
	public void testGetSameMethods() {
		ReflectionAdapter reflectionAdapter = new ReflectionAdapter(Territory.class, TerritoryModel.class);

		Assert.assertTrue(reflectionAdapter.getSameMethods(Territory.class, TerritoryModel.class).size() == 3);
	}

	@Test
	public void testAppHasAGreeting() {
		ReflectionAdapter reflectionAdapter = new ReflectionAdapter(Territory.class, TerritoryModel.class);

		Territory territory = new Territory();
		territory.setId(11);
		territory.setName("robert");
		territory.setNumber(22);

		TerritoryModel territoryModel = reflectionAdapter.get(territory);
		Assert.assertEquals(territory.getId(), territoryModel.getId());
		Assert.assertEquals(territory.getName(), territoryModel.getName());
		Assert.assertEquals(territory.getNumber(), territoryModel.getNumber());
	}
}
